import os
from jinja2 import Environment, FileSystemLoader
from loguru import logger
from datetime import datetime
from app.core.models import PingStats

HTML_TEMPLATE = """
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>NetPulse Report - {{ stats.host }}</title>
    <style>
        body { font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif; background-color: #1e1e2e; color: #cdd6f4; margin: 0; padding: 20px; }
        .container { max-width: 800px; margin: 0 auto; background-color: #181825; padding: 20px; border-radius: 10px; box-shadow: 0 4px 6px rgba(0,0,0,0.3); }
        h1 { color: #89b4fa; text-align: center; }
        .stats-grid { display: grid; grid-template-columns: repeat(auto-fit, minmax(200px, 1fr)); gap: 20px; margin-top: 20px; }
        .stat-card { background-color: #313244; padding: 15px; border-radius: 8px; text-align: center; }
        .stat-value { font-size: 24px; font-weight: bold; color: #a6e3a1; margin-top: 10px; }
        .stat-label { font-size: 14px; color: #bac2de; }
        .footer { text-align: center; margin-top: 30px; font-size: 12px; color: #6c7086; }
    </style>
</head>
<body>
    <div class="container">
        <h1>NetPulse Ping Report</h1>
        <p style="text-align: center;">Target Host: <strong>{{ stats.host }}</strong></p>
        <p style="text-align: center;">Generated on: {{ date }}</p>
        
        <div class="stats-grid">
            <div class="stat-card">
                <div class="stat-label">Packets Sent</div>
                <div class="stat-value">{{ stats.packets_sent }}</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Packets Received</div>
                <div class="stat-value">{{ stats.packets_received }}</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Packet Loss</div>
                <div class="stat-value">{{ "%.2f"|format(stats.packet_loss) }}%</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Min Latency</div>
                <div class="stat-value">{{ "%.2f"|format(stats.min_latency) }} ms</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Max Latency</div>
                <div class="stat-value">{{ "%.2f"|format(stats.max_latency) }} ms</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Avg Latency</div>
                <div class="stat-value">{{ "%.2f"|format(stats.avg_latency) }} ms</div>
            </div>
            <div class="stat-card">
                <div class="stat-label">Jitter</div>
                <div class="stat-value">{{ "%.2f"|format(stats.jitter) }} ms</div>
            </div>
        </div>
        
        <div class="footer">
            Generated by NetPulse | A Professional Network Monitoring Tool
        </div>
    </div>
</body>
</html>
"""

class ReportService:
    def __init__(self, output_dir="reports"):
        self.output_dir = output_dir
        os.makedirs(self.output_dir, exist_ok=True)

    def generate_html_report(self, stats: PingStats) -> str:
        try:
            from jinja2 import Template
            template = Template(HTML_TEMPLATE)
            html_content = template.render(
                stats=stats,
                date=datetime.now().strftime("%Y-%m-%d %H:%M:%S")
            )
            
            filename = f"report_{stats.host.replace('.', '_')}_{datetime.now().strftime('%Y%m%d%H%M%S')}.html"
            filepath = os.path.join(self.output_dir, filename)
            
            with open(filepath, "w", encoding="utf-8") as f:
                f.write(html_content)
                
            logger.info(f"Report generated successfully: {filepath}")
            return filepath
        except Exception as e:
            logger.error(f"Error generating report: {e}")
            return ""
